### ISSUE TITLE
Outdated `six` dependency? 

### ISSUE THREAD

**Issue by diego898** [coursera-dl/coursera#314]
Hello!

I am running OSX Yosemite, and python 2.7.6. I've installed everything with `pip`, 

```
my-MacBook-Air:coursera my$ pip install --upgrade -r requirements.txt
Requirement already up-to-date: beautifulsoup4>=4.1.3 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: coverage>=3.7 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: html5lib>=1.0b2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: nose>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: requests>=2.4.3 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: six>=1.5.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: mock>=1.0.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 7))
my-MacBook-Air:coursera my$
```

when I try and run `./coursera-dl --help` I get:

```
my-MacBook-Air:coursera my$ ./coursera-dl --help
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/Users/my/src/coursera/coursera/coursera_dl.py", line 90, in <module>
    assert V(six.__version__) >= V('1.5'), "Upgrade six!" + _see_url
AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139
```

however, pip tells me:

```
my-MacBook-Air:coursera my$ pip show six
---
Name: six
Version: 1.9.0
Location: /Library/Python/2.7/site-packages
Requires:
```

I've seen #139, but I installed everything using the recommended `pip` way in the first place. What could be the problem?

**Comment by mxamin** [comment]
I don't know where the problem is exactly, but creating and activating a `virtualenv` and then running `pip` will solve your problem.

**Comment by diego898** [comment]
how exactly would I create the new virtualenv? What packages do I "include" in it?

**Comment by mxamin** [comment]
Install *virtualenv*: `pip install virtualenv`
Change your current directory to cloned *coursera* repository and create a new *virtualenv*: `virtualenv venv`
Activate *virtualenv*: `source venv/bin/activate`. Now your command prompt should start with `(venv)`.
Install requirement packages: `pip install -r requirements.txt`. Now you are good to go.

**Comment by hustlijian** [comment]
use:

    sudo easy_install six

will upgrade `six`.

reason: 

mac already have six module in `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py`, 

when use `pip`, six module will install in ` /Library/Python/2.7/site-packages`,

 use the `easy_install` will change the lib path for `six`.

**Comment by rbrito** [comment]
@hustlijian, yes, a system version of the modules may, indeed influence with the installation of newer versions of said modules.

@diego898, do you still see the problems after the hint of @hustlijian? It would be nice if anybody could write a paragraph or two to our documentation regarding this gotcha.

Thanks.

**Comment by victorwestmann** [comment]
Is this solved? Can I help somehow? :)

**Comment by ma-ver-ick** [comment]
sudo easy_install six

helped me (my problem had the same error message 'upgrade six') on a fresh MacOS 10.10 install.

thanks @hustlijian !

**Comment by ilovejs** [comment]
sudo pip uninstall six
sudo easy_install six
