### ISSUE TITLE
'sslv3 alert handshake failure' on Debian Stable

### ISSUE THREAD

**Issue by MatthiasJaeger** [coursera-dl/coursera#323]
Just got an error "sslv3 alert handshake failure".

Operating system: Debian Stable, 64bit, newest security updates 
libssl1.0.0-version: 1.0.1e-2+deb7u16
coursera-dl-version: 3.1.1

Error Message:
```
$ coursera-dl positivepsych-001
Coursera-dl v3.1.1 (html.parser)
Credentials found in .netrc file
Logging in as ' *** '...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 133, in login
    res = opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 439, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 439, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1219, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

**Comment by mxamin** [comment]
You are using a different application, post your issue [here](https://github.com/dgorissen/coursera-dl).

**Comment by rbrito** [comment]
The project that you are using is not ours. Yes, we know that it is
confusing, but there are at least two projects with the same name.

That being said, you are invited to try our program, as that problem is
fixed in our master branch:

https://github.com/coursera-dl/coursera/commit/46320cfec9b5e9e42fe6c7b1ca602347e3ee4420
