### ISSUE TITLE
Handshake failure

### ISSUE THREAD

**Issue by foxyreign** [coursera-dl/coursera#327]
foxyreign@Foxy-Ubuntu:~/Dropbox/Coursera$ coursera-dl -u adrian@....com textretrieval-001
Coursera-dl v3.0.1 (html.parser)
Password: 
Logging in as 'adrian@....com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.0.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 588, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 105, in login
    res = opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

**Comment by rbrito** [comment]
Hi, Adrian.

On Mar 28 2015, Adrian Cuyugan wrote:
> foxyreign@Foxy-Ubuntu:~/Dropbox/Coursera$ coursera-dl -u adrian@foxyreign.com textretrieval-001
> Coursera-dl v3.0.1 (html.parser)
(...)

The project that you are using is not ours. Yes, we know that it is
confusing, but there are at least two projects with the same name.

That being said, you are invited to try our program, as that problem is
fixed in our master branch:

https://github.com/coursera-dl/coursera/commit/46320cfec9b5e9e42fe6c7b1ca602347e3ee4420


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br
