### ISSUE TITLE
Failed Downloads - Connection aborted.', TimeoutError(10060)

### ISSUE THREAD

**Issue by harshab80** [coursera-dl/coursera#328]
Hello, I am downloading a course and after downloading each lecture it fails with below message.
If I restart will download next lecture and fails. Can you help me?

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 516, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python34\lib\socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "C:\Python34\lib\ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python34\lib\ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected
 party did not properly respond after a period of time, or established connectio
n failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 362, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py",
line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\packages\six.py"
, line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 516, in urlopen
    body=body, headers=headers)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python34\lib\http\client.py", line 1172, in getresponse
    response.begin()
  File "C:\Python34\lib\http\client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "C:\Python34\lib\http\client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python34\lib\socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "C:\Python34\lib\ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python34\lib\ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', Time
outError(10060, 'A connection attempt failed because the connected party did not
 properly respond after a period of time, or established connection failed becau
se connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\\coursera-dl", l
ine 6, in <module>
    coursera_dl.main()
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\coursera\courser
a_dl.py", line 932, in main
    result = download_class(args, class_name)
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\coursera\courser
a_dl.py", line 861, in download_class
    args.intact_fnames)
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\coursera\courser
a_dl.py", line 499, in download_lectures
    downloader.download(url, lecfn)
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\coursera\downloa
ders.py", line 43, in download
    self._start_download(url, filename)
  File "C:\Users\dcmsbh\Desktop\coursera-master\coursera-master\coursera\downloa
ders.py", line 280, in _start_download
    r = self.session.get(url, stream=True)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 457, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060,
 'A connection attempt failed because the connected party did not properly respo
nd after a period of time, or established connection failed because connected ho
st has failed to respond', None, 10060, None))

**Comment by harshab80** [comment]
Found out the rootcause, due to some issue download speed was reduced considerably which in turn timedout session. Now it works beautifully :-)

**Comment by Starxyz** [comment]
i met the same problems。could you tell me how you solved it？
