### ISSUE TITLE
urllib3.poolmanager import is missing - something like that...!?

### ISSUE THREAD

**Issue by Make42** [coursera-dl/coursera#331]
I downloaded the latest version, on my Ubuntu 14.4 machine and ran 

.../coursera-master$ sudo pip install -r requirements.txt
.../coursera-master$ sudo apt-get install python-urllib3
.../coursera-master$ ./coursera-dl -u myemail@example.com -p mypasswort aiplan-003

and (still - even after the second command) get the error (with "......" being anonymization)

Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "....../coursera-master/coursera/coursera_dl.py", line 72, in <module>
    from .cookies import (
  File "....../coursera-master/coursera/cookies.py", line 13, in <module>
    from requests.packages.urllib3.poolmanager import PoolManager
ImportError: No module named packages.urllib3.poolmanager

Why is that and what can I do?

**Comment by rbrito** [comment]
Dear @Make42,

On Apr 07 2015, Make42 wrote:
> I downloaded the latest version, on my Ubuntu 14.4 machine and ran 
> 
> .../coursera-master$ sudo pip install -r requirements.txt

Please, don't install python packages as root in your system. They may
interfere negatively with the rest of your system, especially when you
upgrade your operating system.

> .../coursera-master$ sudo apt-get install python-urllib3

Which version of `python-urllib3` is this? Does following my advice in
https://github.com/coursera-dl/coursera/issues/330#issuecomment-90756627
help a bit or not?

(...)
> Traceback (most recent call last):
>   File "./coursera-dl", line 4, in <module>
>     from coursera import coursera_dl
>   File "....../coursera-master/coursera/coursera_dl.py", line 72, in <module>
>     from .cookies import (
>   File "....../coursera-master/coursera/cookies.py", line 13, in <module>
>     from requests.packages.urllib3.poolmanager import PoolManager
> ImportError: No module named packages.urllib3.poolmanager
> 
> Why is that and what can I do?

I'm just guessing here, but the problem *may* be that what you have
installed a version of requests (via pip) that requires a urllib3 that is
newer than what you have.  In other words, they may not be in sync.


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by Make42** [comment]
Hello, how can I deinstall the packages I installed with pip via sudo and reinstall them without sudo?

I ran
*sudo apt-get install python-bs4 python-requests python-html5lib python-urllib3 python-six python-openssl python-ndg-httpsclient python-pyasn1 python-nose python-mock*
and all but *python-ndg-httpsclient* where installed. "python-ndg-httpsclient can not be found" is the message. Anyway, this did not help. The errror message from coursera-dl stayed the same as above.

How do I find out, which version *python-urllib3* is?

**Comment by rbrito** [comment]
Hi.

On Apr 08 2015, Make42 wrote:
> Hello, how can I deinstall the packages I installed with pip via sudo and
> reinstall them without sudo?

Humm, I honestly don't know of a clean procedure. The closest that I know of
is to take a look at pip uninstall (executed via sudo). You can take a look
at the packages that were locally installed by taking a look under
/usr/local.

Also, pip list will give you a list of all python modules that you have
installed. Perhaps pip list --local will let you know the ones that you
installed by yourself.

For more details, please take a look at the output of pip list --help and
pip --help in general.


> sudo apt-get install python-bs4 python-requests python-html5lib python-urllib3 python-six python-openssl python-ndg-httpsclient python-pyasn1 python-nose python-mock

OK.

> and all but *python-ndg-httpsclient* where installed.
> "python-ndg-httpsclient can not be found" is the message.

Then your distribution doesn't have packages that are new enough. :(  You
may try upgrading to the new Ubuntu that will be released in a few days (it
will have all these packages and should be pretty stable at this point).

> Anyway, this did not help. The errror message from coursera-dl stayed the same as above.

I suggest, then, that you use the following recipe which I suggested and
@Cxrille tested:

https://github.com/coursera-dl/coursera/issues/330#issuecomment-90478921

> How do I find out, which version *python-urllib3* is?

You can try, before uninstalling everything, to use one of:

    dpkg -s python-urllib3 (this gives you the version under control of dpkg)
    pip show urllib3

I hope that this helps. If it does, then I guess that I can document this on
the README and close this bug, perhaps?


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by Make42** [comment]
dpkg -s python-urllib3 (this gives you the version under control of dpkg)
    pip show urllib3
works in order to show the version.

The recipe https://github.com/coursera-dl/coursera/issues/330#issuecomment-90478921 worked. I am able to download coursera courses again. Thanks!

**Comment by Make42** [comment]
Ok, here is something strange. I don't think, I should have to repeat the recipe every time I restart the computer, should I? Because I followed it a week ago, and now I had to repeat it again in order to get coursera-dl working. I had coursera-dl downloaded on an external harddrive and also run on the external harddrive. I don't have the harddrive with me right now, so I downloaded coursera-dl again on my computer. However, I can't see how that would be a reason for the issue.

**Comment by Cxrille** [comment]
@Make42, you need to activate your virtualenv each time you want to use it (source bin/activate). Python packages installed in your virtualenv with pip install won't be available system-wide.

**Comment by holocronweaver** [comment]
In Ubuntu 14.04 I have the same problem, which is solved the same way @Make42 suggested by creating a Python virtualenv. This is a far from ideal solution though. Is there no way to make a regular pip install work independent of OS? I mostly just want system wide access to coursera-dl in a fresh terminal without any additional commands.

**Comment by rbrito** [comment]
Hi there.

On Jun 06 2015, Jesse Johnson wrote:
> In Ubuntu 14.04 I have the same problem, which is solved the same way
> @Make42 suggested by creating a Python virtualenv. This is a far from
> ideal solution though.

I completely agree. In fact, this problem is a nuisance that has consumed
far more of my time than many other features that I have implemented so far
in the program.

But there is one catch, which I would like to know:

* What exactly are the messages that you get (with --debug being specified,
  please)?

* How did you install coursera-dl? By cloning our repository? By using pip
  (that is, "pip install coursera")? Note that, to install via pip, you
  *must* use coursera, but *not* coursera-dl, as that is a different project
  (yes, I know that this is an unfortunate fact of life).

* What are the python modules that you have installed? The output of "pip freeze"
  would be helpful here.

* What version of Python do you have?

I am writing a document that tells the users if their installation is good
enough or not to access SSL/TLS-based sites like coursera that disabled
SSLv3.

I may post a draft here, and I would love feedback from the users, both in
testing my instructions and also in the phrasing.

> Is there no way to make a regular pip install work independent of OS? I
> mostly just want system wide access to coursera-dl in a fresh terminal
> without any additional commands.

Sure. That's how I like to use my programs also (and that's how I use the
program myself).


Hope this helps,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by holocronweaver** [comment]
* Messages I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 72, in <module>
    from .cookies import (
  File "/usr/local/lib/python2.7/dist-packages/coursera/cookies.py", line 13, in <module>
    from requests.packages.urllib3.poolmanager import PoolManager
ImportError: No module named packages.urllib3.poolmanager
```

* Install method: `pip install coursera` (makes no difference if I use `--user` or not, same message)

* pip freeze output:
```
Warning: cannot find svn location for apsw==3.8.2-r1
BeautifulSoup==3.2.1
Cheetah==2.4.4
Cython==0.20.1post0
Fabric==1.8.2
Jinja2==2.7.2
Mako==0.9.1
Markdown==2.4
MarkupSafe==0.18
MySQL-python==1.2.3
PAM==0.4.2
Pillow==2.3.0
PyOpenGL==3.0.2
Pygments==1.6
SQLAlchemy==0.8.4
SecretStorage==2.0.0
Sphinx==1.2.2
Twisted==13.2.0
Twisted-Conch==13.2.0
Twisted-Core==13.2.0
Twisted-Lore==13.2.0
Twisted-Mail==13.2.0
Twisted-Names==13.2.0
Twisted-News==13.2.0
Twisted-Runner==13.2.0
Twisted-Web==13.2.0
Twisted-Words==13.2.0
adium-theme-ubuntu==0.3.4
## FIXME: could not find svn URL in dependency_links for this package:
apsw==3.8.2-r1
apt-xapian-index==0.45
argparse==1.2.1
autokey==0.90.4
beautifulsoup4==4.2.1
bzr==2.7.0dev1
ccsm==0.9.11.3
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
compizconfig-python==0.9.11.3
configglue==1.1.2
configobj==4.7.2
coursera==0.0.3
cssselect==0.9.1
cssutils==0.9.10
cvxopt==1.1.4
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
deluge==1.3.6
dirspec==13.10
dnspython==1.11.1
docutils==0.11
duplicity==0.6.23
f.lux-indicator-applet==1.1.8
gourmet==0.17.3
html5lib==1.0b6
httplib2==0.8
ipython==2.0.0-dev
jedi==0.9.0
keyring==5.3
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lockfile==0.8
lxml==3.3.3
matplotlib==1.3.1
mechanize==0.2.5
mercurial==2.8.2
ndg-httpsclient==0.4.0
netifaces==0.8
nose==1.3.1
numexpr==2.2.2
numpy==1.8.2
oauth==1.0.1
oauthlib==0.6.1
offlineimap==6.5.4
oneconf==0.3.7
openpyxl==1.7.0
openshot==1.4.3
pandas==0.12.0-169-gd680f13
paramiko==1.10.1
patsy==0.2.1
pexpect==3.1
piston-mini-client==0.7.5
pomodoro-indicator==0.1.0
protobuf==2.5.0
psutil==1.2.1
py==1.4.20
pyOpenSSL==0.13
pyasn1==0.1.7
pychm==0.8.4
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pyenchant==1.6.5
pygame==1.9.1release
pygobject==3.12.0
pygpgme==0.3
pygtkspellcheck==3.0
pyinotify==0.9.4
pyopencl==2013.3
pyparsing==2.0.1
pyserial==2.6
pysmbc==1.0.14.1
pysqlite==1.0.1
pytest==2.5.2
python-apt==0.9.3.5ubuntu1
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
python-distutils-extra==2.38
python-libtorrent==0.16.13
python-xlib==0.14
pytools==2013.5.7
pytz==2012c
pyxdg==0.25
pyzmq==14.0.1
reportlab==3.0
requests==2.7.0
rhythmbox-ubuntuone==13.10
roman==2.0.0
scipy==0.13.3
service-factory==0.1.2
sessioninstaller==0.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.5.2
smartypants==1.6.0.3
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
statsmodels==0.5.0
system-service==0.1.6
tables==3.1.1
tornado==3.1.1
trash-cli==0.12.7
ubuntu-tweak==0.8.7
ubuntuone-storage-protocol==13.10
urllib3==1.10.4
vboxapi==1.0
virtualenv==1.11.4
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xdiagnose==3.6.3build2
xlrd==0.9.2
xlwt==0.7.5
zope.interface==4.0.5
```

* Python 2.7.6

**Comment by rbrito** [comment]
What do you get if you change line 13 of /usr/local/lib/python2.7/dist-packages/coursera/cookies.py

from

    from requests.packages.urllib3.poolmanager import PoolManager

to

    from urllib3.poolmanager import PoolManager

Does it change anything?

One thing that may be biting you here is that you seem to be using a mix of Debian's/Ubuntu's requests/urllib3 packages. The upstream version of requests includes an embedded copy of urllib3, but Debian's/Ubuntu's don't.

Please, let me know if you have problems here or not.

Thanks,

Rogério Brito.

**Comment by holocronweaver** [comment]
Making the requested change results in Coursera throwing an assert:
```
assert V(requests.__version__) >= V('2.4'), "Upgrade requests!" + _see_url
AssertionError: Upgrade requests! See https://github.com/coursera-dl/coursera/issues/139
```
which I take to mean the `requests` package you mentioned needs to be upgraded. 

However, in Ubuntu 14.04 the printer control panel depends on the `python-requests` package, and thus I can't remove it. Is there another way to solve this?

**Comment by superabe** [comment]
Try to remove the ```python-request``` using ```apt-get``` then reinstall ```requests``` using ```pip```. Good luck.

**Comment by holocronweaver** [comment]
As I said, I can't do that because the printer control panel depends on the `python-request` package being installed.

**Comment by superabe** [comment]
I don't have a printer connected. What if you reinstalled the ```requests``` through ```pip``` and then reinstall the control panel? Would the control panel work?

**Comment by rbrito** [comment]
Hi, @holocronweaver and others.

On Jun 07 2015, Jesse Johnson wrote:
> As I said, I can't do that because the printer control panel depends on
> the `python-request` package being installed.

First of all, it is strange that I didn't get your reply to me, but that I
got the rest of the conversation. I only saw the replies coming here.

Anyway, since you have a recent enough version of requests, can you do me a
favor?

* What do you get when you comment the assert line?
* If you fire up a python interpreter, what do you get with:

    import requests
    requests.__version__
    import sys
    sys.path

Depending on what you get, I may relax some of the assertions, so that we
kill this bug for good, at least.

I'm actually only waiting for workarounds/fixes to this thing to release a
new version of the package on pip, so I'd appreciate a quick answer.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Oh, a few more requests (pun intended):  :)

On Jun 08 2015, Rogério Brito wrote:
>     import requests
>     requests.__version__
>     import sys
>     sys.path

      requests.__path__
      import urllib3
      urllib3.__version__
      urllib3.__path__

Also, what do you get from pip if you type:

    pip show requests

What I want to know here is if you are using a local copy of requests
(installed via pip) or if you are using the version from ubuntu.

The strange thing here is that my (Debian) installation of requests does not
include urllib3, *BUT* it is properly patched to hook into the separate
installed urllib3 also taken from the Debian repository.  (Why yours isn't
working is a separate bug that's not a problem here with coursera-dl).

While I personally use all the dependencies from Debian, I continuously test
both manually (with tox) and automatically (via Travis) with "pristine"
upstream packages installed from pip in virtualenvs.

OK, I guess that those answers would lead us into a solution that makes the
program work.


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Oops. Github thought that my new comment was only made of quotes. Please, "open" it to see it what I'm requesting.

**Comment by rbrito** [comment]
@holocronweaver, Ping.

Can you check what I described above in comments https://github.com/coursera-dl/coursera/issues/331#issuecomment-109849026 and https://github.com/coursera-dl/coursera/issues/331#issuecomment-109849810 ?

@Make42, do you still have the problem mentioned in this bug? If so, information from you would be valuable too.

**Comment by Make42** [comment]
@rbrito, I haven't used coursera-dl for a couple of weeks now. There is a lot changing here right now: What installation process should I use to check this out?

**Comment by holocronweaver** [comment]
Sorry for delay. Things got crazy go nuts at work.

Removing the assert appears to allow `coursera-dl` to run as usual.

* Output from `sys.path`:
```
['',
 '/usr/local/bin',
 '/usr/local/lib/python3.4/dist-packages/patsy-0.2.1_dev-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/PyWeaver-0.1-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/statsmodels-0.6.0-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/GridDataFormats-0.2.4-py3.4.egg',
 '/usr/local/lib/python3.4/dist-packages/pandas-0.14.1_25_ga797b28-py3.4-linux-x86_64.egg',
 '/usr/local/lib/python3.4/dist-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg',
 '/usr/lib/python3/dist-packages',
 '/home/jesse/local/lib/python',
 '/home/jesse',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/local/lib/python3.4/dist-packages/IPython/extensions',
 '/home/jesse/.ipython']
```
* requests version and path: `2.2.1 ['/usr/lib/python3/dist-packages/requests']`
* urlib3 version and path: `1.7.1 ['/usr/lib/python3/dist-packages/urllib3']`

**Comment by rbrito** [comment]
@holocronweaver, can you post also the following two pieces of information:

* the output of `which pip` (so that we can see which pip you are using, if the one that comes buitin or one that was upgraded/installed via pip)
* the output of `pip show requests` (so that we can see which version of requests in your python import path is the one being used---note that the one output with pip is 2.7.0, while the one that you imported with the python interpreter is 2.2.1).

The situation stinks a lot, as I've researched a bit more. See the following issues

https://bugs.debian.org/771349
https://bugs.debian.org/788383
https://github.com/kennethreitz/requests/pull/2375
https://github.com/kennethreitz/requests/pull/2567
https://lists.debian.org/debian-python/2015/05/msg00021.html
https://lists.debian.org/debian-python/2015/05/msg00022.html

Thanks,

Rogério Brito.

**Comment by holocronweaver** [comment]
* `which pip`: `/usr/bin/pip`
* `pip show requests`: nothing is output, maybe I had to reinstall the one included by the `python-requests` package to ensure the Ubuntu printer control panel worked.

**Comment by rbrito** [comment]
Hi.

On Jun 11 2015, Jesse Johnson wrote:
> * `pip show requests`: nothing is output, maybe I had to reinstall the one
> included by the `python-requests` package to ensure the Ubuntu printer
> control panel worked.

This is super strange, since pip should show something, even for packages
that are installed via the distribution. In my case:

,----[ pip show requests ]
| ---
| Name: requests
| Version: 2.7.0
| Location: /usr/lib/python2.7/dist-packages
| Requires: 
`----

I guess that supporting this kind of hybrid/broken situation is probably not
the scope of coursera-dl, given that the problematic packages really come
from the distribution.

I think that you should, perhaps, file a bug against Ubuntu to note that
their version of python-requests should adopt the glue code (which is really
small) from upstream requests to link requests properly with urllib3 and
chardet.

If you can live with some breakage for a few moments with your printer
(well, perhaps it may not even break), it would be nice to know if getting
updated versions of the following packages make coursera-dl work:

* python-requests
* python-urllib3
* python-chardet
* python-ndg-httpsclient
* python-openssl
* python-pyasn1

For python-ndg-httpsclient, you may need to install packages from the latest
stable Ubuntu release. If you take all precautions, it should be painless to
revert these changes if they break your programs (just downgrade the
packages).

Oh, BTW, I am interested in the entire stack trace that happened when you
lowered the assertion of requiring a newer version of requests.

I really hope that I either find a solution, or document workarounds and/or
cautions, as I have already put a lot of effort trying to understand the
breakage of the half-baked modules.

You know what? I am starting to think that, while inconvenient, there is a
stronger reason than I thought at first for using a virtual environment and
have the dependencies all isolated from the rest of the system.

Perhaps distributing a python wheel (with all the bundled dependencies) is
the way to go.  Too bad that the (py)openssl module depends on compilation
against the system's openssl and binaries are not provided... :(


Thanks for the feedback,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by holocronweaver** [comment]
I updated my comment on Github a few minutes after making it. I had mistakenly queried for singular `request` instead of the plural `requests`.

I think the real problem is how Python packaging works. Distro packages should be separated from those installed by other means, and distro software should specifically use those packages and not rely on environment variables, freeing users and package maintainers from having to worry about what versions distros require. Independent package managers like `pip` should check dependency version requirements and, if necessary, download a newer version of a package than is provided by the distro. That way distros don't have to worry about what Python packages the user installs, and Python package managers don't have to worry about what distros require to operate.

Maybe I am oversimplifying the situation, but that seems like a simple enough solution to me. It would probably require cooperation between Linux distros and core Python devs to define a distro maintained package space, and a way to reference the distro packages within Python, but I am surprised this isn't the way things are already done.

I agree that a virtual environment seems to be the best way to go for now. After all, Ubuntu 14.04 is a long term release and will a) probably not be patched even if we make a bug report (ubuntu devs are, in my experience, unresponsive to small 'niche' bugs), and b) will be used for at least another two or three years by a sizeable portion of Linux users.

I will get that full stack trace to you shortly. Please ping me back if I take more than a couple days. Currently travelling and I may not get a chance to look at my TODO list.

**Comment by rbrito** [comment]
Hi.

Is this bug still happening? I would love to close this issue if it is not happening anymore.

Thanks,

Rogério.

**Comment by holocronweaver** [comment]
I no longer have an Ubuntu 14.04 system to test on, but on Ubuntu 15.04 I obtained `coursera` via `pip3` and everything works fine. Thus I am not sure if the problem on Ubuntu 14.04 is resolved.

**Comment by Make42** [comment]
Being on Ubuntu 14.4:

$ sudo pip install coursera
$ coursera-dl -u xxxxxxxx -p xxxxxxxx modelthinking-004
Downloading class: modelthinking-004
Starting new HTTPS connection (1): class.coursera.org
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Starting new HTTPS connection (1): www.coursera.org
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 944, in main
    result = download_class(args, class_name)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 842, in download_class
    username=args.username, password=args.password)
  File "/usr/local/lib/python2.7/dist-packages/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/usr/local/lib/python2.7/dist-packages/coursera/cookies.py", line 160, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/usr/local/lib/python2.7/dist-packages/coursera/cookies.py", line 115, in login
    headers=headers, allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
