### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by mkevac** [coursera-dl/coursera#341]
```
$ ./coursera-dl -u marko@kevac.org -p *** matrix-002
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/home/marko/tmp/coursera/coursera/coursera_dl.py", line 72, in <module>
    from .cookies import (
  File "/home/marko/tmp/coursera/coursera/cookies.py", line 19, in <module>
    from .utils import mkdir_p, random_string
  File "/home/marko/tmp/coursera/coursera/utils.py", line 33, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

How to reproduce:
```
$ mkvirtualenv --system-site-packages main
$ git clone git@github.com:coursera-dl/coursera.git
$ pip install -r requirements
$ ./coursera-dl -u marko@kevac.org -p *** matrix-002
```

**Comment by mkevac** [comment]
Creating virtualenv without --system-site-packages helped
