### ISSUE TITLE
ConnectionError: ('Connection aborted.', ResponseNotReady())

### ISSUE THREAD

**Issue by Calvin-he** [coursera-dl/coursera#347]
Downloading class: algo2-004
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "/home/calvin/Public/scrapyenv/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.0', 'console_scripts', 'coursera-dl')()
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/coursera-0.0.0-py2.7.egg/coursera/coursera_dl.py", line 928, in main
    result = download_class(args, class_name)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/coursera-0.0.0-py2.7.egg/coursera/coursera_dl.py", line 826, in download_class
    username=args.username, password=args.password)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/coursera-0.0.0-py2.7.egg/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/coursera-0.0.0-py2.7.egg/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/coursera-0.0.0-py2.7.egg/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/calvin/Public/scrapyenv/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

**Comment by azarudeen90** [comment]
Try logging out of the web version and run the script. Please use the --clear-cache option along the way.

**Comment by azarudeen90** [comment]
@Calvin-he is it working now? So that we can close it.

**Comment by danmbox** [comment]
No, it doesn't work, same error. Could --clear-cache and logging out really help? It's never made a difference in the past...

**Comment by danmbox** [comment]
It seems that #348 and #349 are duplicates of #347

**Comment by ankitshah009** [comment]
Same issue still there for my fresh trial for another course?
Did not work with the clear-cache option

**Comment by ekianjo** [comment]
I have the same issue here.

**Comment by Calvin-he** [comment]
@azarudeen90  the issue still exists.

@rbrito I am using cousera-dl on Python 2.8.7, Windows 7.  Following are the python packages I have installed. 
>
(couseraenv) PS somefolder\cousera> pip list
beautifulsoup4 (4.3.2)
cffi (0.9.2)
coursera (0.0.0)
cryptography (0.8.2)
enum34 (1.0.4)
html5lib (1.0b3)
ndg-httpsclient (0.3.3)
pip (1.5.6)
pyasn1 (0.1.7)
pycparser (2.12)
pyOpenSSL (0.15.1)
requests (2.6.2)
setuptools (3.6)
six (1.9.0)
urllib3 (1.10.3)

**Comment by rbrito** [comment]
Hi,

On May 05 2015, Calvin wrote:
> @azarudeen90  the issue still exists.

Bummer.

> @rbrito I am using cousera-dl on Python 2.8.7, Windows 7.  Following are
> the python packages I have installed.

I guess that you meant Python 2.7.8, right? If that's correct, can you
please try to upgrade to Python 2.7.9? It contains fixes related to SSL, as
far as I know.

> (couseraenv) PS somefolder\cousera> pip list
> beautifulsoup4 (4.3.2)
> cffi (0.9.2)
> coursera (0.0.0)
> cryptography (0.8.2)
> enum34 (1.0.4)
> html5lib (1.0b3)
> ndg-httpsclient (0.3.3)
> pip (1.5.6)
> pyasn1 (0.1.7)
> pycparser (2.12)
> pyOpenSSL (0.15.1)
> requests (2.6.2)
> setuptools (3.6)
> six (1.9.0)
> urllib3 (1.10.3)

Thanks for providing your list of packages. Can you upgrade your packages
here? In particular, urllib3 and requests would be great to have upgraded,
but others would be nice too.

Once we have (at least) Python updated, I guess that we could have a more
common ground so that I can start looking more closely.


Thanks for your report,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by danmbox** [comment]
@rbrito Are you going to require python 2.7.9? It would be unfortunate for e.g. Ubuntu LTS (14.04) users.

**Comment by Calvin-he** [comment]
@rbrito , following your suggestion,  I upgraded Python 2.7.9 from 2.7.8. No errors reported, it's ok now. Thanks very much.

**Comment by rbrito** [comment]
Hi, Dan.

On May 05 2015, Dan Muresan wrote:
> @rbrito Are you going to require python 2.7.9? It would be unfortunate for
> e.g. Ubuntu LTS (14.04) users.

As far as I am concerned, I really don't care what version of Python you
use, but there were some changes in Python and I don't know precisely how to
make the program more robust to work with the changes in OpenSSL + Python +
Coursera dropping SSLv3.

I have some ideas for experimenting, but I would need one such environment
to test. Do you have one? Would you be willing to test the changes?


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Hi, Calvin.

On May 06 2015, Calvin wrote:
> @rbrito , following your suggestion, I upgraded Python 2.7.9 from 2.7.8.
> No errors reported, it's ok now. Thanks very much.

So, your only change was to upgrade Python to 2.7.9 and nothing else? Or did
you install some extra package (or a newer version of some package)?  It
would be great to know so that we can finally nail down this and document it
for good.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by danmbox** [comment]
@rbrito sure, I can test things on Ubuntu Trusty (python 2.7.6). In fact, at the moment I need to run coursera-dl in a Vivid (15.04) Docker container, which is not optimal. I would settle for a virtualenv, but I can't upgrade the Python version.

**Comment by Calvin-he** [comment]
@rbrito yes, I  only change was to upgrade Python to 2.7.9 and nothing else.  I did it on Windows 7.

**Comment by azarudeen90** [comment]
Hi @rbrito I'm also facing the same issue after the few patch updates. 

argparse (1.3.0)
beautifulsoup4 (4.3.2)
coursera (0.0.3)
html5lib (1.0b3)
pip (1.5.6)
pyasn1 (0.1.7)
requests (2.6.2)
setuptools (7.0)
six (1.9.0)
urllib3 (1.10.3)

python 2.7.9 on windows 7.

**Comment by rbrito** [comment]
@azarudeen90, are you using "vanilla" python 2.7.9 and not cygwin?

Can you people having problems with this try to install the python package `ndg-httpsclient`? It should (hopefully) pull in `pyOpenSSL` and a recent enough requests library will try to use it.

The problem seems to occur inside requests (see the last lines of the trace) and you can, perhaps, have better luck with both the packages that I mentioned and also with an updated `requests` module.

You can see which modules of yours are not up-to-date with `pip list --outdated`.

The funny thing is that there are connections being made. By the way, can you include the verbose log?

This bug is keeping me from releasing a new version to pypi and I'm annoyed. I would like to fix it as well as possible.


Thanks,

Rogério.

**Comment by azarudeen90** [comment]
Now its working fine

**Comment by azarudeen90** [comment]
@Calvin-he Could you please close this issue if your issue got solved.

**Comment by danmbox** [comment]
@rbrito you should explicitly require python 2.7.9 if you can't solve the issues for older versions.

By the way, did you ever check the integrity of the downloads? We've had unsolvable problems with python-requests (e.g. chunks of an mp4 downloaded out-of-order) in the *other* coursera-dl and were forced to downgrade.

**Comment by rbrito** [comment]
Hi, Dan.

On May 14 2015, Dan Muresan wrote:
> @rbrito you should explicitly require python 2.7.9 if you can't solve the
> issues for older versions.

Yes, I still have hope of making it work for older installations.

The problem is that other project also seem to be having problems with
Python version earlier than 2.7.9. See, for example the snippet from
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning:

    > Certain Python platforms (specifically, versions of Python earlier
    > than 2.7.9) have restrictions in their ssl module that limit the
    > configuration that urllib3 can apply. In particular, this can cause
    > HTTPS requests that would succeed on more featureful platforms to
    > fail, and can cause certain security features to be unavailable.

    > If you encounter this warning, it is strongly recommended you upgrade to a
    > newer Python version, or that you use pyOpenSSL as described in the
    > OpenSSL / PyOpenSSL section.


> By the way, did you ever check the integrity of the downloads?

No, I have never worried about integrity of the downloads, because I seem to:

* Have been using requests for longer than the other project.
* No user ever reported any corruption problem.
* I, myself, have never had any problems (and I use this program daily).
* And I don't know against what I could check the integrity of the
  downloads, as coursera doesn't seem to offer checksums of their videos.

What kind of integrity checking do you have in mind? I would love to check
some hashes (md5, sha1, sha256, whatever), but I doubt that they offer that.

If that's not what you had in mind, I'd love to know your idea.

> We've had unsolvable problems with python-requests (e.g. chunks of an mp4
> downloaded out-of-order) in the *other* coursera-dl and were forced to
> downgrade.

Super strange and creepy.

Just out of curiosity: are you still using the other coursera-dl project?


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by shixudongleo** [comment]
Same problem on Mac OSX Yosomite.  I am using Python 2.7.9, requests and urllib3 are updated to latest version. I have also installed pyOpenSSL. What other solutions should I try?

Downloading class: digital-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/shixudongleo/Projects/coursera/coursera/coursera_dl.py", line 960, in main
    result = download_class(args, class_name)
  File "/Users/shixudongleo/Projects/coursera/coursera/coursera_dl.py", line 858, in download_class
    username=args.username, password=args.password)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.3.2)
certifi (2015.4.28)
cov-core (1.15.0)
coverage (3.7.1)
execnet (1.3.0)
gnureadline (6.3.3)
html5lib (1.0b6)
ipdb (0.8)
ipython (3.1.0)
Jinja2 (2.7.3)
jsonschema (2.4.0)
keyring (5.3)
MarkupSafe (0.23)
matplotlib (1.4.3)
mistune (0.5.1)
mock (1.0.1)
nose (1.3.6)
numpy (1.9.2)
pbr (0.10.8)
pip (6.1.1)
ptyprocess (0.4)
py (1.4.27)
pyasn1 (0.1.7)
Pygments (2.0.2)
pyparsing (2.0.3)
pytest (2.7.0)
pytest-cov (1.8.1)
pytest-xdist (1.12)
python-dateutil (2.4.2)
pytz (2015.2)
pyzmq (14.6.0)
requests (2.6.2)
scikit-learn (0.16.1)
scipy (0.15.1)
setuptools (15.0)
six (1.9.0)
stevedore (1.4.0)
terminado (0.5)
tornado (4.1)
urllib3 (1.10.4)
virtualenv (12.1.1)
virtualenv-clone (0.2.5)
virtualenvwrapper (4.5.0)

Python 2.7.9

**Comment by azarudeen90** [comment]
I don't see pyOpenssl in the list buddy.  There is another https library mentioned above this comments . Why don't u check it out

**Comment by shixudongleo** [comment]
I checked, I did install the PyOpenSSL module, but my pip list is not correct. Anyway, here is the correct one. And I also checkout ndg-httpsclient. The error remains:

Downloading class: digital-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/shixudongleo/Projects/coursera/coursera/coursera_dl.py", line 960, in main
    result = download_class(args, class_name)
  File "/Users/shixudongleo/Projects/coursera/coursera/coursera_dl.py", line 858, in download_class
    username=args.username, password=args.password)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/Users/shixudongleo/Projects/coursera/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.3.2)
certifi (2015.4.28)
cffi (0.9.2)
cov-core (1.15.0)
coverage (3.7.1)
cryptography (0.9)
enum34 (1.0.4)
execnet (1.3.0)
gnureadline (6.3.3)
html5lib (1.0b6)
idna (1.1)
ipaddress (1.0.7)
ipdb (0.8)
ipython (3.1.0)
Jinja2 (2.7.3)
jsonschema (2.4.0)
keyring (5.3)
MarkupSafe (0.23)
matplotlib (1.4.3)
mistune (0.5.1)
mock (1.0.1)
ndg-httpsclient (0.4.0)
nose (1.3.6)
numpy (1.9.2)
pbr (0.10.8)
pip (6.1.1)
ptyprocess (0.4)
py (1.4.27)
pyasn1 (0.1.7)
pycparser (2.13)
Pygments (2.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pytest (2.7.0)
pytest-cov (1.8.1)
pytest-xdist (1.12)
python-dateutil (2.4.2)
pytz (2015.2)
pyzmq (14.6.0)
requests (2.6.2)
scikit-learn (0.16.1)
scipy (0.15.1)
setuptools (15.0)
six (1.9.0)
stevedore (1.4.0)
terminado (0.5)
tornado (4.1)
urllib3 (1.10.4)
virtualenv (12.1.1)
virtualenv-clone (0.2.5)
virtualenvwrapper (4.5.0)

**Comment by azarudeen90** [comment]
Hey Guys i was just examining the request flow. with the --debug command. unfortunately during the get request of the class/index or the lecture/index page we are getting a response code 301 or 302. I'm  not sure why the redirection error is coming in. but my guess is the cookies or the authentication token is not persisting with respect to session.

**Comment by Glavin001** [comment]
I am also experiencing `Connection aborted` with most of the courses I try.

**Comment by rbrito** [comment]
On Jun 16 2015, Glavin Wiechert wrote:
> I am also experiencing `Connection aborted` with most of the courses I try.

@Glavin001 and other people, can you send details, please?

What operating system/version, python version (`python --version`), and
version of modules are you using (`pip list`)? Are you using a virtual
environment?

Is the problem transient? You mentioned "with most of the courses", which
seems to indicate that it works for some courses, but not for others. This
is surprising, as I have never seen this behavior myself.

The more details that you include, the more likely I am to (try to) find a
common pattern in your bug reports.


Thanks,

Rogério.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Once again, github thought that I was only posting a pithy one-line response and seemed to ignore the rest. Here goes the text:

----

@Glavin001 and other people, can you send details, please?

What operating system/version, python version (`python --version`), and version of modules are you using (`pip list`)? Are you using a virtual environment?

Is the problem transient? You mentioned "with most of the courses", which seems to indicate that it works for some courses, but not for others. This is surprising, as I have never seen this behavior myself.

The more details that you include, the more likely I am to (try to) find a common pattern in your bug reports.


Thanks,

Rogério.

**Comment by Glavin001** [comment]
Absolutely @rbrito! I actually had to run off to a dentist appointment, which is why my message was so short. It was more so a placeholder / reminder for me to come back and add more information when I had time. Thanks for the comprehensive list of things I should include. I am not as experienced of a Python developer, so this is helpful.

---

### My Setup

- Operating System: Mac OS X 10.10.3 Yosemite
- Python 2.7.9
- No virtual environment for this, I installed with `pip install coursera`
- `pip list`:

```
$ pip list
alabaster (0.7.3)
amqp (1.4.5)
anyjson (0.3.3)
argparse (1.3.0)
autobahn (0.6.4)
autopep8 (1.1.1)
Babel (1.3)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.3.2)
billiard (3.3.0.17)
bottle (0.12.5)
catkin-pkg (0.2.8)
celery (3.1.11)
certifi (14.5.14)
coursera (0.0.3)
distribute (0.7.3)
docutils (0.12)
Flask (0.10)
Flask-Login (0.2.9)
flask-mongoengine (0.7.0)
Flask-OpenID (1.0)
Flask-Sockets (0.1)
Flask-WTF (0.9.4)
gevent (1.0)
gevent-websocket (0.9.1)
git-sweep (0.1.1)
gitdb (0.6.3)
GitPython (0.3.4)
gnureadline (6.3.3)
greenlet (0.4.2)
html5lib (1.0b6)
ipython (3.1.0)
itsdangerous (0.23)
Jinja2 (2.7.3)
jsonschema (2.4.0)
kombu (3.0.16)
Leapcast (0.1.3, /Users/glavin/Documents/Project Dev/leapcast)
MarkupSafe (0.23)
matplotlib (1.4.3)
msgpack-python (0.4.6)
music21 (1.8.1)
nose (1.3.6)
numpy (1.9.2)
pbr (0.10.8)
pep8 (1.6.2)
Pillow (2.8.1)
pip (1.5.6)
pyasn1 (0.1.7)
PyAudio (0.2.7)
Pygments (2.0.2)
pyparsing (2.0.3)
Pyro (3.16)
Pyro4 (4.22)
python-dateutil (2.4.2)
python-openid (2.2.5)
pytz (2015.2)
PyYAML (3.11)
pyzmq (13.1.0)
requests (2.6.2)
rosdep (0.11.2)
rosdistro (0.4.2)
rosinstall (0.7.5)
rosinstall-generator (0.1.11)
rospkg (1.0.35)
scikit-learn (0.15.2)
scipy (0.15.1)
serpent (1.4)
setuptools (15.1)
six (1.9.0)
smmap (0.8.5)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.7)
sqlparse (0.1.15)
stevedore (1.4.0)
Theano (0.7.0)
tornado (4.1)
Twisted (13.1.0)
urllib3 (1.10.4)
vboxapi (1.0)
vcstools (0.1.36)
virtualenv (12.1.1)
virtualenv-clone (0.2.5)
virtualenvwrapper (4.5.0)
Werkzeug (0.9.4)
wsgiref (0.1.2)
wstool (0.1.6)
WTForms (1.0.5)
zerorpc (0.4.4)
zope.interface (4.0.5)
```

### My problems

So this may likely be because I am misusing this tool. Here are the commands I am trying:

#### Working

- `coursera-dl -u <user> -p <pass> --on-demand machine-learning`
  - Originally I was missing the `--on-demand` however after reading about the Courses Types from https://learner.coursera.help/hc/en-us/articles/203879739 I realized my mistake

#### Not Working

Connection Aborted error message.

I had found https://github.com/coursera-dl/coursera/issues/59#issue-10869667 and was trying to download those courses as tests for `coursera-dl`.

- `coursera-dl -u <user> -p <pass> neuralnets-2012-001`
- `coursera-dl -u <user> -p <pass> algo2-2012-001`
- `coursera-dl -u <user> -p <pass> proglang-2012-001`

Note that if I manually go to https://class.coursera.org/neuralnets-2012-001/class/index in my web browser (Chrome, 43.0) I am redirected back to https://class.coursera.org/neuralnets-2012-001 as @azarudeen90 indicates in [the comment above](https://github.com/coursera-dl/coursera/issues/347#issuecomment-103611624).

##### Example error message

```
Downloading class: neuralnets-2012-001
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 944, in main
    result = download_class(args, class_name)
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 842, in download_class
    username=args.username, password=args.password)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

**Comment by Glavin001** [comment]
More that do not work:

- `coursera-dl -u <user> -p <pass> rprog-015`
- `coursera-dl -u <user> -p <pass> compneuro-003`

**Comment by rbrito** [comment]
Hi, @Glavin001 and others.

Is this bug still relevant?

I posted https://github.com/coursera-dl/coursera-dl/issues/377#issuecomment-131268395 with some steps that would allow us to better understand the bug.

If, indeed, you still have the problems mentioned here, I would appreciate seeing `coursera-dl` being run in a virtual environment (see instructions at: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems).


Thanks,

Rogério Brito.

**Comment by balta2ar** [comment]
@akaralar Are you using the latest version from github?

**Comment by akaralar** [comment]
@balta2ar no I installed it with pip and got the error, then installed via virtualenv method from github and it works

**Comment by akaralar** [comment]
@balta2ar and it doesn't work now, it was working in a virtualenv just a few days ago :(

**Comment by Leibniz137** [comment]
```
coursera_dl version 0.6.1
Downloading class: algo-005
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1304, in main
    if download_class(args, class_name):
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1278, in download_class
    return download_old_style_class(args, class_name)
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1124, in download_old_style_class
    username=args.username, password=args.password)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 173, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/usr/local/lib/python2.7/site-packages/coursera/cookies.py", line 141, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

```
$ python --version
Python 2.7.11
```

```
$ pip list
astroid (1.0.1)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
beautifulsoup4 (4.4.1)
bottle (0.11.6)
certifi (2016.2.28)
coursera-dl (0.6.1)
cycler (0.10.0)
Cython (0.24)
Django (1.5.3)
elasticsearch (0.4.4)
functools32 (3.2.3.post2)
gnureadline (6.3.3)
html5lib (1.0b8)
ipython (3.1.0)
Jinja2 (2.7.1)
jsonschema (2.5.1)
keyring (9.0)
logilab-common (0.61.0)
Markdown (2.5.1)
MarkupSafe (0.18)
matplotlib (1.5.1)
mercurial (2.7)
nose (1.3.7)
numpy (1.11.0)
pep8 (1.4.6)
Pillow (3.2.0)
Pillow-PIL (0.1.dev0)
pip (8.1.2)
protobuf (3.0.0b2)
py (1.4.26)
pyapi-gitlab (7.5.0)
pyasn1 (0.1.9)
pyes (0.20.1)
pyflakes (0.8.1)
pylint (1.1.0)
pyparsing (2.1.1)
pystache (0.5.3)
pytest (2.6.4)
python-dateutil (2.5.3)
pytz (2016.4)
pyzmq (15.2.0)
requests (2.6.2)   # <--- LOOK!
scikit-learn (0.17.1)
scipy (0.17.0)
setuptools (20.10.1)
singledispatch (3.4.0.3)
six (1.10.0)
tensorflow (0.8.0)
tornado (4.3)
urllib3 (1.16)
vboxapi (1.0)
virtualenv (1.11.6)
wheel (0.29.0)
```
It looks like the issue is with the ```2.6.2``` version of requests.

I also found that using a virtualenv fixed the issue. This works because, in an initially empty virtualenv, pip has to download all the dependencies, and by default it's going to pull in the latest version of each package. As of this writing the latest version of requests is ```2.10.0```

Crucially, downloads also worked outside the virtualenv after running ```pip install --upgrade requests```


Additionally, looking at the output of pip list for other comments, it looks like everyone with this issue was running requests version ```2.6.2```

##### see:
- https://github.com/coursera-dl/coursera-dl/issues/347#issuecomment-99277117
- https://github.com/coursera-dl/coursera-dl/issues/347#issuecomment-101220470
- https://github.com/coursera-dl/coursera-dl/issues/347#issuecomment-102631872
- https://github.com/coursera-dl/coursera-dl/issues/347#issuecomment-225452362




NOTE: you should probably upgrade pip itself before upgrading requests: ```pip install --upgrade pip```

**Comment by balta2ar** [comment]
@Leibniz137 Thank you very much for your detective work! I've updated requests version in requirements.txt to 2.10.0.
