### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

### ISSUE THREAD

**Issue by Make42** [coursera-dl/coursera#348]
Hello,
I did everything written in https://github.com/coursera-dl/coursera/issues/330#issuecomment-90478921 to install coursera-dl on my Kubuntu 14.4, but I only get the error

$ ./coursera-dl -u me@example.com -p mypassword procmin-002
Downloading class: procmin-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/coursera/coursera/coursera_dl.py", line 928, in main
    result = download_class(args, class_name)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/coursera/coursera/coursera_dl.py", line 826, in download_class
    username=args.username, password=args.password)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/coursera/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/coursera/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/coursera/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/PhoenixData/homeSettings/Downloads/Coursera/coursera/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

What should I do?

**Comment by lenciel** [comment]
Exactly the same issue here. I wrote quite easy implementation and I got the same error.

**Comment by rbrito** [comment]
Hi.

As this seems to be the same as issue #347, I'm closing this bug and kindly asking you people to report what you see in messages to that issue. This way, I can see what changes and what doesn't regarding your bug.

I would appreciate if you could help by sending (to issue #347) the list of packages installed, beginning with the version of Python and the modules that you have installed.

Thanks.
