### ISSUE TITLE
doesn't connect to Coursera

### ISSUE THREAD

**Issue by searoso** [coursera-dl/coursera#349]
I use Ubuntu 14.10, looks like I do something wrong, but I'm sticking to the instruction tightly.
```
(testf)cepreu@cepreu-HP-ENVY-Sleekbook-4:~/coursera-master/testf/coursera$ ./coursera-dl --debug -u SK* -p *  modelthinking-009
root[main] Downloading class: modelthinking-009
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /tmp/cepreu_coursera_dl_cache/cookies/SKaunov@Gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /modelthinking-009 HTTP/1.1" 302 None
root[login] Forging cookie header: csrftoken=tH0h4GzMnYKB0KM8i2CK; csrf2_token_FW3zcJEu=4hOk0z1BtAPOULYcTcEIUPAS.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /modelthinking-009/auth/auth_redirector?type=login&subtype=normal HTTP/1.1" 302 None
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/cepreu/coursera-master/testf/coursera/coursera/coursera_dl.py", line 928, in main
    result = download_class(args, class_name)
  File "/home/cepreu/coursera-master/testf/coursera/coursera/coursera_dl.py", line 826, in download_class
    username=args.username, password=args.password)
  File "/home/cepreu/coursera-master/testf/coursera/coursera/cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/cepreu/coursera-master/testf/coursera/coursera/cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "/home/cepreu/coursera-master/testf/coursera/coursera/cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/cepreu/coursera-master/testf/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

**Comment by cndpzc** [comment]
I use windows 7, python version 2.7.8, got the same error.

File "D:/github/coursera/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "D:/github/coursera\coursera\coursera_dl.py", line 928, in main
    result = download_class(args, class_name)
  File "D:/github/coursera\coursera\coursera_dl.py", line 826, in download_class
    username=args.username, password=args.password)
  File "D:/github/coursera\coursera\cookies.py", line 337, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "D:/github/coursera\coursera\cookies.py", line 167, in get_authentication_cookies
    down_the_wabbit_hole(session, class_name)
  File "D:/github/coursera\coursera\cookies.py", line 135, in down_the_wabbit_hole
    r = session.get(auth_redirector_url)
  File "D:\devtool\python27\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "D:\devtool\python27\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\devtool\python27\lib\site-packages\requests\sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\devtool\python27\lib\site-packages\requests\sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "D:\devtool\python27\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "D:\devtool\python27\lib\site-packages\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())

**Comment by rbrito** [comment]
Hi.

As this seems to be the same as issue #347, I'm closing this bug and kindly asking you people to report what you see in messages to that issue. This way, I can see what changes and what doesn't regarding your bug.

I would appreciate if you could help by sending the list of packages installed, beginning with the version of Python and the modules that you have installed.

Thanks.
