### ISSUE TITLE
Assertion error while downloading courses

### ISSUE THREAD

**Issue by nitingupta180** [coursera-dl/coursera#355]
I am getting below error while downloading any course material.

---------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 91, in <module>
    assert V(six.__version__) >= V('1.5'), "Upgrade six!" + _see_url
AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139

**Comment by rbrito** [comment]
Hi.

What are the versions of your modules (like the last line of the error
says)? You can list them by using:

    pip list

Also, you can specify further information about your `six` installation via
the following command:

    pip show six

You can list your outdated modules by using:

    pip list --outdated


Hope this helps,

Rogério Brito.


-- 
Rogério Brito : rbrito@{mackenzie,ime.usp}.br : GPG key 1024D/7C2CAEB8
http://www.ime.usp.br/~rbrito : http://meusite.mackenzie.com.br/rbrito
Projects: algorithms.berlios.de : lame.sf.net : vrms.alioth.debian.org

**Comment by nitingupta180** [comment]
Result of pip list
-------------------
altgraph (0.10.2)
bdist-mpkg (0.5.0)
beautifulsoup4 (4.3.2)
bonjour-py (0.3)
coursera (0.0.3)
coursera-dl (3.1.1)
cov-core (1.15.0)
coverage (3.7.1)
execnet (1.3.0)
html5lib (1.0b6)
keyring (5.3)
macholib (1.5.1)
matplotlib (1.3.1)
mechanize (0.2.5)
mock (1.0.1)
modulegraph (0.10.4)
numpy (1.8.0rc1)
pip (6.1.1)
py (1.4.27)
py2app (0.7.3)
pyasn1 (0.1.7)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
pytest (2.7.0)
pytest-cov (1.8.1)
pytest-xdist (1.12)
python-dateutil (1.5)
pytz (2013.7)
requests (2.7.0)
scipy (0.13.0b1)
setuptools (1.1.6)
six (1.9.0)
Twisted (13.2.0)
urllib3 (1.10.4)
virtualenv (1.10.1)
xattr (0.6.4)
zope.interface (4.1.1)

===============================================================================
Result of pip show six
----------------------------
Metadata-Version: 2.0
Name: six
Version: 1.9.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Library/Python/2.7/site-packages
Requires: 

============================================================================

Result of pip list --outdated 

--------------------------------

/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
virtualenv (Current: 1.10.1 Latest: 12.1.1 [wheel])
altgraph (Current: 0.10.2 Latest: 0.12 [sdist])
Could not find a version that satisfies the requirement bonjour-py (from versions: )
Some externally hosted files were ignored as access to them may be unreliable (use --allow-external bonjour-py to allow).
macholib (Current: 1.5.1 Latest: 1.7 [sdist])
matplotlib (Current: 1.3.1 Latest: 1.4.3 [wheel])
modulegraph (Current: 0.10.4 Latest: 0.12 [sdist])
numpy (Current: 1.8.0rc1 Latest: 1.9.2 [wheel])
py2app (Current: 0.7.3 Latest: 0.9 [sdist])
pyOpenSSL (Current: 0.13.1 Latest: 0.15.1 [wheel])
pyparsing (Current: 2.0.1 Latest: 2.0.3 [wheel])
python-dateutil (Current: 1.5 Latest: 2.4.2 [wheel])
pytz (Current: 2013.7 Latest: 2015.4 [wheel])
scipy (Current: 0.13.0b1 Latest: 0.15.1 [wheel])
setuptools (Current: 1.1.6 Latest: 15.2 [wheel])
Twisted (Current: 13.2.0 Latest: 15.1.0 [sdist])
xattr (Current: 0.6.4 Latest: 0.7.5 [sdist])
zope.interface (Current: 4.1.1 Latest: 4.1.2 [sdist])
pyobjc-core (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Accounts (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-AddressBook (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-AppleScriptKit (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-AppleScriptObjC (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Automator (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-CFNetwork (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Cocoa (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Collaboration (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-CoreData (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-CoreLocation (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-CoreText (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-DictionaryServices (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-EventKit (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-ExceptionHandling (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-FSEvents (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-InputMethodKit (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-InstallerPlugins (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-InstantMessage (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-LatentSemanticMapping (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-LaunchServices (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Message (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-OpenDirectory (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-PreferencePanes (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-PubSub (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-QTKit (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Quartz (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-ScreenSaver (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-ScriptingBridge (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-SearchKit (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-ServiceManagement (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-Social (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-SyncServices (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-SystemConfiguration (Current: 2.5.1 Latest: 3.0.4 [sdist])
pyobjc-framework-WebKit (Current: 2.5.1 Latest: 3.0.4 [sdist])

**Comment by rbrito** [comment]
Hi.

Just to isolate things and to better understand what may be happening, can you create a virtual environment?

I'm using the same version of `six` and I don't see any problems... Nobody else reported problems with the `six` module for ages...


Thanks,

Rogério Brito.

**Comment by dolphin-zs** [comment]
When you run into the dependency error, such as "Upgrade six!". Maybe you could use 
import six, and check six.__version__ and six.__file__ .

**Comment by sagunms** [comment]
I had the same problem and finally solved it using python3 pip. Python 2.7 pip didn't work for me.

**Mac OSX (Yosemite):**
```
brew install python3
pip3 install coursera
```
**Ubuntu 14.04 LTS**
```
sudo apt-get install python3 python3-pip
sudo pip3 install coursera
```
**Usage Example**
```
cd ~/Downloads/MyAwesomeCourses
coursera-dl -u you@email.com -p 'yourP$$wd' algorithmicthink2-002
```

Hope it helps you.
